### PR TITLE
Add gpt-3.5-turbo

### PR DESCRIPTION
**Pull request by Ukenn2112**

### CODE REVIEW

**Comment by yetone** [comment]
Awesome ！！！！

**Comment by Jane8899** [comment]
AI news daily consumed in 5 minutes or less. 30,000+ already subscribed. We have readers from Google, Meta, a16z, Microsoft, Amazon, and many more

**Comment by Moophier** [comment]
好

**Comment by Moophier** [comment]
朝阳暮色，坐也思君

**Pull request merged**
